backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - label: "Produse"
    name: "products"
    files:
      - label: "Lista de produse"
        name: "products_list"
        file: "data/products.json"
        editor:
          preview: false
        fields:
          - label: "Produse"
            name: "items"
            widget: "list"
            collapsed: false
            fields:
              - { label: "SKU", name: "sku", widget: "string" }
              - { label: "Titlu", name: "title", widget: "string" }
              - { label: "Preț (RON)", name: "price", widget: "number", value_type: "float", min: 0, step: 0.01 }
              - { label: "Imagine", name: "image", widget: "image", choose_url: true }
              - { label: "Mărimi", name: "sizes", widget: "list", field: {label: "Mărime", name: "size", widget: "string"} }
              - { label: "Culori", name: "colors", widget: "list", field: {label: "Culoare", name: "color", widget: "string"} }
              - { label: "Stoc", name: "stock", widget: "number", min: 0, step: 1 }
              - { label: "Categorie", name: "category", widget: "string" }
