backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: simple

collections:
  - name: "store"
    label: "Magazin"
    files:
      - file: "content/products.json"
        label: "Produse"
        name: "products"
        fields:
          - label: "Lista produse"
            name: "items"
            widget: list
            fields:
              - { label: "Titlu", name: "title", widget: "string" }
              - { label: "SKU", name: "sku", widget: "string" }
              - { label: "Preț (TVA inclus)", name: "price", widget: "number" }
              - { label: "Se vinde doar la set de 10 bucăți", name: "pack10", widget: "boolean", default: true }
              - { label: "Mărimi", name: "sizes", widget: "list", field: { label: "Mărime", name: "size", widget: "string" } }
              - { label: "Culori", name: "colors", widget: "list", field: { label: "Culoare", name: "color", widget: "string" } }
              - { label: "Imagini", name: "images", widget: "list", field: { label: "Imagine", name: "image", widget: "image" } }
              - { label: "Descriere", name: "description", widget: "text" }
